package com.wnn.springboot.model;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_PSW
     *
     * @mbggenerated
     */
    private String loginPsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.GROUP_CODE
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ROLE_CODE
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.POST
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.OFFICE
     *
     * @mbggenerated
     */
    private String office;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.TELEPHONE_NO
     *
     * @mbggenerated
     */
    private String telephoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    private String emailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.FAX_NO
     *
     * @mbggenerated
     */
    private String faxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.BRANCH_CODE
     *
     * @mbggenerated
     */
    private String branchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATED_USER
     *
     * @mbggenerated
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATED_DATE
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LAST_UPD_USER
     *
     * @mbggenerated
     */
    private String lastUpdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LAST_UPD_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ACTIVE_IND
     *
     * @mbggenerated
     */
    private String activeInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CHG_PWD_DATE
     *
     * @mbggenerated
     */
    private Date chgPwdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.FAILED_COUNT
     *
     * @mbggenerated
     */
    private String failedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LAST_FAILEDDATE
     *
     * @mbggenerated
     */
    private Date lastFaileddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REQ_CHANGEPWD_IND
     *
     * @mbggenerated
     */
    private String reqChangepwdInd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ID
     *
     * @return the value of sys_user.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ID
     *
     * @param userId the value for sys_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_NAME
     *
     * @return the value of sys_user.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_NAME
     *
     * @param userName the value for sys_user.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_PSW
     *
     * @return the value of sys_user.LOGIN_PSW
     *
     * @mbggenerated
     */
    public String getLoginPsw() {
        return loginPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_PSW
     *
     * @param loginPsw the value for sys_user.LOGIN_PSW
     *
     * @mbggenerated
     */
    public void setLoginPsw(String loginPsw) {
        this.loginPsw = loginPsw == null ? null : loginPsw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.GROUP_CODE
     *
     * @return the value of sys_user.GROUP_CODE
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.GROUP_CODE
     *
     * @param groupCode the value for sys_user.GROUP_CODE
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ROLE_CODE
     *
     * @return the value of sys_user.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ROLE_CODE
     *
     * @param roleCode the value for sys_user.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.POST
     *
     * @return the value of sys_user.POST
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.POST
     *
     * @param post the value for sys_user.POST
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.OFFICE
     *
     * @return the value of sys_user.OFFICE
     *
     * @mbggenerated
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.OFFICE
     *
     * @param office the value for sys_user.OFFICE
     *
     * @mbggenerated
     */
    public void setOffice(String office) {
        this.office = office == null ? null : office.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.TELEPHONE_NO
     *
     * @return the value of sys_user.TELEPHONE_NO
     *
     * @mbggenerated
     */
    public String getTelephoneNo() {
        return telephoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.TELEPHONE_NO
     *
     * @param telephoneNo the value for sys_user.TELEPHONE_NO
     *
     * @mbggenerated
     */
    public void setTelephoneNo(String telephoneNo) {
        this.telephoneNo = telephoneNo == null ? null : telephoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL_ADDRESS
     *
     * @return the value of sys_user.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL_ADDRESS
     *
     * @param emailAddress the value for sys_user.EMAIL_ADDRESS
     *
     * @mbggenerated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.FAX_NO
     *
     * @return the value of sys_user.FAX_NO
     *
     * @mbggenerated
     */
    public String getFaxNo() {
        return faxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.FAX_NO
     *
     * @param faxNo the value for sys_user.FAX_NO
     *
     * @mbggenerated
     */
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo == null ? null : faxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.BRANCH_CODE
     *
     * @return the value of sys_user.BRANCH_CODE
     *
     * @mbggenerated
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.BRANCH_CODE
     *
     * @param branchCode the value for sys_user.BRANCH_CODE
     *
     * @mbggenerated
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode == null ? null : branchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATED_USER
     *
     * @return the value of sys_user.CREATED_USER
     *
     * @mbggenerated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATED_USER
     *
     * @param createdUser the value for sys_user.CREATED_USER
     *
     * @mbggenerated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATED_DATE
     *
     * @return the value of sys_user.CREATED_DATE
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATED_DATE
     *
     * @param createdDate the value for sys_user.CREATED_DATE
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LAST_UPD_USER
     *
     * @return the value of sys_user.LAST_UPD_USER
     *
     * @mbggenerated
     */
    public String getLastUpdUser() {
        return lastUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LAST_UPD_USER
     *
     * @param lastUpdUser the value for sys_user.LAST_UPD_USER
     *
     * @mbggenerated
     */
    public void setLastUpdUser(String lastUpdUser) {
        this.lastUpdUser = lastUpdUser == null ? null : lastUpdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LAST_UPD_DATE
     *
     * @return the value of sys_user.LAST_UPD_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for sys_user.LAST_UPD_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdDate(Date lastUpdDate) {
        this.lastUpdDate = lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ACTIVE_IND
     *
     * @return the value of sys_user.ACTIVE_IND
     *
     * @mbggenerated
     */
    public String getActiveInd() {
        return activeInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ACTIVE_IND
     *
     * @param activeInd the value for sys_user.ACTIVE_IND
     *
     * @mbggenerated
     */
    public void setActiveInd(String activeInd) {
        this.activeInd = activeInd == null ? null : activeInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CHG_PWD_DATE
     *
     * @return the value of sys_user.CHG_PWD_DATE
     *
     * @mbggenerated
     */
    public Date getChgPwdDate() {
        return chgPwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CHG_PWD_DATE
     *
     * @param chgPwdDate the value for sys_user.CHG_PWD_DATE
     *
     * @mbggenerated
     */
    public void setChgPwdDate(Date chgPwdDate) {
        this.chgPwdDate = chgPwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.FAILED_COUNT
     *
     * @return the value of sys_user.FAILED_COUNT
     *
     * @mbggenerated
     */
    public String getFailedCount() {
        return failedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.FAILED_COUNT
     *
     * @param failedCount the value for sys_user.FAILED_COUNT
     *
     * @mbggenerated
     */
    public void setFailedCount(String failedCount) {
        this.failedCount = failedCount == null ? null : failedCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LAST_FAILEDDATE
     *
     * @return the value of sys_user.LAST_FAILEDDATE
     *
     * @mbggenerated
     */
    public Date getLastFaileddate() {
        return lastFaileddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LAST_FAILEDDATE
     *
     * @param lastFaileddate the value for sys_user.LAST_FAILEDDATE
     *
     * @mbggenerated
     */
    public void setLastFaileddate(Date lastFaileddate) {
        this.lastFaileddate = lastFaileddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REQ_CHANGEPWD_IND
     *
     * @return the value of sys_user.REQ_CHANGEPWD_IND
     *
     * @mbggenerated
     */
    public String getReqChangepwdInd() {
        return reqChangepwdInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REQ_CHANGEPWD_IND
     *
     * @param reqChangepwdInd the value for sys_user.REQ_CHANGEPWD_IND
     *
     * @mbggenerated
     */
    public void setReqChangepwdInd(String reqChangepwdInd) {
        this.reqChangepwdInd = reqChangepwdInd == null ? null : reqChangepwdInd.trim();
    }
}